// ---------------------------------------------------------------------------
// Demo beneficiary book — real petroleum, trade & finance companies worldwide.
//
// A rich, professional set of counterparties for the demo / showcase account
// (user u3, demo@mccgva.ch). These are real, well-known companies across the
// Petroleum/Energy, International Trade/Commodities and Finance/Banking sectors,
// paired with plausible (NOT real) banking coordinates so the demo is realistic
// and immediately usable in payments, commodity trading and institutional
// transactions.
//
// Scope & isolation: this list is only ever applied to the demo user. It is
// seeded into that user's namespaced localStorage and merged into the durable
// Neon copy (client_beneficiaries) on the next sync, exactly like the rest of
// the demo data. No other account is touched.
//
// Relationship (Customer / Provider) and sector are recorded in `notes` since
// the Beneficiary shape models counterparties uniformly; `type` distinguishes
// corporates from financial institutions.
// ---------------------------------------------------------------------------

import type { Beneficiary } from "@/lib/beneficiaries-store"

// ISO yyyy-mm-dd for `n` days before now.
function dateAgo(n: number): string {
  return new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString().slice(0, 10)
}
// ISO timestamp for `n` days before now.
function daysAgo(n: number): string {
  return new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString()
}

/**
 * The full demo beneficiary book. Returned as a function because the
 * created/last-used/AML dates are relative to "now".
 *
 * IDs BEN-DEMO-0001..0003 intentionally match the original demo seed so the
 * backfill merge never duplicates the pre-existing established counterparties.
 */
export function demoBeneficiaries(): Beneficiary[] {
  return [
    // === Trade / Commodities — established trading houses ===================
    {
      id: "BEN-DEMO-0001",
      type: "corporate",
      name: "Glencore International AG",
      alias: "Glencore",
      accountNumber: "623852957",
      iban: "CH9300762011623852957",
      swiftBic: "UBSWCHZH80A",
      bankName: "UBS Switzerland AG",
      bankAddress: "Bahnhofstrasse 45, 8001 Zürich",
      bankCountry: "Switzerland",
      beneficiaryAddress: "Baarermattstrasse 3",
      beneficiaryCity: "Baar",
      beneficiaryCountry: "Switzerland",
      beneficiaryPostalCode: "6340",
      currency: "USD",
      status: "active",
      isFavorite: true,
      createdAt: daysAgo(140),
      lastUsed: daysAgo(22),
      totalTransactions: 18,
      totalVolume: 612_000_000,
      registrationNumber: "CHE-105.927.534",
      vatNumber: "CHE-105.927.534",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(30),
      notes: "Provider · Trade / Commodities — crude & refined products",
    },
    {
      id: "BEN-DEMO-0002",
      type: "corporate",
      name: "Vitol SA",
      alias: "Vitol Geneva",
      accountNumber: "12345678009",
      iban: "CH5604835012345678009",
      swiftBic: "CRESCHZZ80A",
      bankName: "Credit Suisse (Switzerland) Ltd",
      bankAddress: "Paradeplatz 8, 8001 Zürich",
      bankCountry: "Switzerland",
      beneficiaryAddress: "Boulevard du Pont-d'Arve 28",
      beneficiaryCity: "Geneva",
      beneficiaryCountry: "Switzerland",
      beneficiaryPostalCode: "1205",
      currency: "EUR",
      status: "active",
      isFavorite: true,
      createdAt: daysAgo(120),
      lastUsed: daysAgo(15),
      totalTransactions: 12,
      totalVolume: 280_000_000,
      registrationNumber: "CHE-101.482.090",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(25),
      notes: "Provider · Trade / Commodities — energy trading house",
    },
    {
      id: "BEN-DEMO-0003",
      type: "financial_institution",
      name: "Barclays Bank PLC",
      alias: "Barclays London",
      accountNumber: "60161331926819",
      iban: "GB29NWBK60161331926819",
      swiftBic: "BARCGB22",
      bankName: "Barclays Bank PLC",
      bankAddress: "1 Churchill Place, London E14 5HP",
      bankCountry: "United Kingdom",
      beneficiaryAddress: "1 Churchill Place",
      beneficiaryCity: "London",
      beneficiaryCountry: "United Kingdom",
      beneficiaryPostalCode: "E14 5HP",
      currency: "GBP",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(110),
      lastUsed: daysAgo(9),
      totalTransactions: 9,
      totalVolume: 156_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(20),
      notes: "Finance / Banking — settlement & correspondent bank",
    },
    {
      id: "BEN-DEMO-0004",
      type: "corporate",
      name: "Trafigura Pte Ltd",
      alias: "Trafigura Singapore",
      accountNumber: "0108765432018",
      swiftBic: "DBSSSGSG",
      bankName: "DBS Bank Ltd",
      bankAddress: "12 Marina Boulevard, Singapore 018982",
      bankCountry: "Singapore",
      beneficiaryAddress: "10 Collyer Quay, Ocean Financial Centre",
      beneficiaryCity: "Singapore",
      beneficiaryCountry: "Singapore",
      beneficiaryPostalCode: "049315",
      currency: "USD",
      status: "active",
      isFavorite: true,
      createdAt: daysAgo(132),
      lastUsed: daysAgo(11),
      totalTransactions: 14,
      totalVolume: 421_000_000,
      registrationNumber: "201125450G",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(28),
      notes: "Provider · Trade / Commodities — metals & energy logistics",
    },
    {
      id: "BEN-DEMO-0005",
      type: "corporate",
      name: "Mercuria Energy Trading SA",
      alias: "Mercuria Geneva",
      accountNumber: "98761234567",
      iban: "CH5404835098761234567",
      swiftBic: "BCGECHGGXXX",
      bankName: "Banque Cantonale de Genève",
      bankAddress: "Quai de l'Île 17, 1204 Genève",
      bankCountry: "Switzerland",
      beneficiaryAddress: "Rue de Jargonnant 2",
      beneficiaryCity: "Geneva",
      beneficiaryCountry: "Switzerland",
      beneficiaryPostalCode: "1207",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(98),
      lastUsed: daysAgo(7),
      totalTransactions: 8,
      totalVolume: 198_000_000,
      registrationNumber: "CHE-110.345.221",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(18),
      notes: "Customer · Trade / Commodities — gas & power offtake",
    },
    {
      id: "BEN-DEMO-0006",
      type: "corporate",
      name: "Gunvor SA",
      alias: "Gunvor Geneva",
      accountNumber: "11223344556",
      iban: "CH7204835011223344556",
      swiftBic: "CRESCHZZ80A",
      bankName: "Credit Suisse (Switzerland) Ltd",
      bankAddress: "Paradeplatz 8, 8001 Zürich",
      bankCountry: "Switzerland",
      beneficiaryAddress: "Rue du Rhône 80",
      beneficiaryCity: "Geneva",
      beneficiaryCountry: "Switzerland",
      beneficiaryPostalCode: "1204",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(86),
      lastUsed: daysAgo(19),
      totalTransactions: 6,
      totalVolume: 134_000_000,
      registrationNumber: "CHE-103.879.114",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(22),
      notes: "Provider · Trade / Commodities — crude oil & products",
    },
    {
      id: "BEN-DEMO-0007",
      type: "corporate",
      name: "Cargill International SA",
      alias: "Cargill Geneva",
      accountNumber: "247852360010",
      iban: "CH2400243124785236001",
      swiftBic: "UBSWCHZH80A",
      bankName: "UBS Switzerland AG",
      bankAddress: "Bahnhofstrasse 45, 8001 Zürich",
      bankCountry: "Switzerland",
      beneficiaryAddress: "14 Chemin de Normandie",
      beneficiaryCity: "Geneva",
      beneficiaryCountry: "Switzerland",
      beneficiaryPostalCode: "1206",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(76),
      lastUsed: daysAgo(31),
      totalTransactions: 5,
      totalVolume: 89_000_000,
      registrationNumber: "CHE-105.991.330",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(26),
      notes: "Customer · Trade / Commodities — agricultural & energy",
    },
    {
      id: "BEN-DEMO-0008",
      type: "corporate",
      name: "Louis Dreyfus Company Suisse SA",
      alias: "LDC Geneva",
      accountNumber: "70001234567",
      iban: "CH7500767000123456789",
      swiftBic: "ABNACHZZ",
      bankName: "ABN AMRO Bank (Switzerland) AG",
      bankAddress: "Beethovenstrasse 33, 8002 Zürich",
      bankCountry: "Switzerland",
      beneficiaryAddress: "29 Route de l'Aéroport",
      beneficiaryCity: "Geneva",
      beneficiaryCountry: "Switzerland",
      beneficiaryPostalCode: "1215",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(64),
      lastUsed: daysAgo(40),
      totalTransactions: 4,
      totalVolume: 72_000_000,
      registrationNumber: "CHE-101.769.480",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(34),
      notes: "Customer · Trade / Commodities — commodity merchant",
    },
    {
      id: "BEN-DEMO-0009",
      type: "corporate",
      name: "Archer Daniels Midland Company",
      alias: "ADM",
      accountNumber: "8810042275",
      swiftBic: "BOFAUS3N",
      bankName: "Bank of America N.A.",
      bankAddress: "100 North Tryon Street, Charlotte, NC 28255",
      bankCountry: "United States",
      beneficiaryAddress: "77 West Wacker Drive",
      beneficiaryCity: "Chicago",
      beneficiaryCountry: "United States",
      beneficiaryPostalCode: "60601",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(58),
      lastUsed: daysAgo(33),
      totalTransactions: 3,
      totalVolume: 51_000_000,
      registrationNumber: "US-ADM-410593",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(29),
      notes: "Customer · Trade / Commodities — agribusiness",
    },

    // === Petroleum / Energy — producers & integrated majors =================
    {
      id: "BEN-DEMO-0010",
      type: "corporate",
      name: "Shell International Trading and Shipping Co Ltd",
      alias: "Shell Trading (STASCO)",
      accountNumber: "18500812345678",
      iban: "GB71CITI18500812345678",
      swiftBic: "CITIGB2L",
      bankName: "Citibank N.A., London",
      bankAddress: "Citigroup Centre, Canada Square, London E14 5LB",
      bankCountry: "United Kingdom",
      beneficiaryAddress: "Shell Centre, York Road",
      beneficiaryCity: "London",
      beneficiaryCountry: "United Kingdom",
      beneficiaryPostalCode: "SE1 7NA",
      currency: "USD",
      status: "active",
      isFavorite: true,
      createdAt: daysAgo(150),
      lastUsed: daysAgo(13),
      totalTransactions: 16,
      totalVolume: 540_000_000,
      registrationNumber: "GB-00811634",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(21),
      correspondentBank: "Citibank N.A., New York",
      correspondentSwift: "CITIUS33",
      notes: "Provider · Petroleum / Energy — crude & product supply",
    },
    {
      id: "BEN-DEMO-0011",
      type: "corporate",
      name: "BP Oil International Ltd",
      alias: "BP Trading",
      accountNumber: "40121512345678",
      iban: "GB06HBUK40121512345678",
      swiftBic: "HBUKGB4B",
      bankName: "HSBC UK Bank plc",
      bankAddress: "1 Centenary Square, Birmingham B1 1HQ",
      bankCountry: "United Kingdom",
      beneficiaryAddress: "Chertsey Road, Sunbury-on-Thames",
      beneficiaryCity: "Sunbury",
      beneficiaryCountry: "United Kingdom",
      beneficiaryPostalCode: "TW16 7BP",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(128),
      lastUsed: daysAgo(24),
      totalTransactions: 11,
      totalVolume: 388_000_000,
      registrationNumber: "GB-00359190",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(27),
      notes: "Provider · Petroleum / Energy — integrated major",
    },
    {
      id: "BEN-DEMO-0012",
      type: "corporate",
      name: "TotalEnergies Trading SA",
      alias: "TotalEnergies Geneva",
      accountNumber: "87000001234567",
      iban: "CH7008387000001234567",
      swiftBic: "BNPACHGG",
      bankName: "BNP Paribas (Suisse) SA",
      bankAddress: "Place de Hollande 2, 1204 Genève",
      bankCountry: "Switzerland",
      beneficiaryAddress: "Rue de l'Industrie 5",
      beneficiaryCity: "Geneva",
      beneficiaryCountry: "Switzerland",
      beneficiaryPostalCode: "1204",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(114),
      lastUsed: daysAgo(17),
      totalTransactions: 10,
      totalVolume: 312_000_000,
      registrationNumber: "CHE-105.812.447",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(23),
      notes: "Provider · Petroleum / Energy — refined products & LNG",
    },
    {
      id: "BEN-DEMO-0013",
      type: "corporate",
      name: "Chevron Products Company",
      alias: "Chevron",
      accountNumber: "7710045820",
      swiftBic: "CHASUS33",
      bankName: "JPMorgan Chase Bank N.A.",
      bankAddress: "383 Madison Avenue, New York, NY 10017",
      bankCountry: "United States",
      beneficiaryAddress: "6001 Bollinger Canyon Road",
      beneficiaryCity: "San Ramon",
      beneficiaryCountry: "United States",
      beneficiaryPostalCode: "94583",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(102),
      lastUsed: daysAgo(36),
      totalTransactions: 7,
      totalVolume: 244_000_000,
      registrationNumber: "US-CHV-339201",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(31),
      notes: "Provider · Petroleum / Energy — integrated major",
    },
    {
      id: "BEN-DEMO-0014",
      type: "corporate",
      name: "Exxon Mobil Oil Corporation",
      alias: "ExxonMobil",
      accountNumber: "3300958879048",
      swiftBic: "CITIUS33",
      bankName: "Citibank N.A.",
      bankAddress: "388 Greenwich Street, New York, NY 10013",
      bankCountry: "United States",
      beneficiaryAddress: "22777 Springwoods Village Parkway",
      beneficiaryCity: "Spring",
      beneficiaryCountry: "United States",
      beneficiaryPostalCode: "77389",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(96),
      lastUsed: daysAgo(38),
      totalTransactions: 6,
      totalVolume: 211_000_000,
      registrationNumber: "US-XOM-118827",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(33),
      notes: "Provider · Petroleum / Energy — integrated major",
    },
    {
      id: "BEN-DEMO-0015",
      type: "corporate",
      name: "Saudi Aramco Products Trading Company",
      alias: "Aramco Trading",
      accountNumber: "000012345678901234",
      iban: "SA8510000012345678901234",
      swiftBic: "NCBKSAJE",
      bankName: "Saudi National Bank",
      bankAddress: "King Abdulaziz Road, Riyadh 11564",
      bankCountry: "Saudi Arabia",
      beneficiaryAddress: "Al Midra Tower, Dhahran",
      beneficiaryCity: "Dhahran",
      beneficiaryCountry: "Saudi Arabia",
      beneficiaryPostalCode: "31311",
      currency: "USD",
      status: "active",
      isFavorite: true,
      createdAt: daysAgo(118),
      lastUsed: daysAgo(14),
      totalTransactions: 13,
      totalVolume: 476_000_000,
      registrationNumber: "SA-ATC-2010100231",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(19),
      notes: "Provider · Petroleum / Energy — national oil company",
    },
    {
      id: "BEN-DEMO-0016",
      type: "corporate",
      name: "Abu Dhabi National Oil Company",
      alias: "ADNOC",
      accountNumber: "1234567890123456",
      iban: "AE540351234567890123456",
      swiftBic: "NBADAEAA",
      bankName: "First Abu Dhabi Bank PJSC",
      bankAddress: "FAB Building, Khalifa Business Park, Abu Dhabi",
      bankCountry: "United Arab Emirates",
      beneficiaryAddress: "Corniche Road, ADNOC Headquarters",
      beneficiaryCity: "Abu Dhabi",
      beneficiaryCountry: "United Arab Emirates",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(92),
      lastUsed: daysAgo(26),
      totalTransactions: 9,
      totalVolume: 298_000_000,
      registrationNumber: "AE-ADNOC-1971",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(24),
      notes: "Provider · Petroleum / Energy — national oil company",
    },
    {
      id: "BEN-DEMO-0017",
      type: "corporate",
      name: "QatarEnergy",
      alias: "QatarEnergy LNG",
      accountNumber: "000000000012345678901",
      iban: "QA94QNBA000000000012345678901",
      swiftBic: "QNBAQAQA",
      bankName: "Qatar National Bank",
      bankAddress: "QNB Tower, West Bay, Doha",
      bankCountry: "Qatar",
      beneficiaryAddress: "QatarEnergy Tower, Corniche Street",
      beneficiaryCity: "Doha",
      beneficiaryCountry: "Qatar",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(84),
      lastUsed: daysAgo(29),
      totalTransactions: 8,
      totalVolume: 266_000_000,
      registrationNumber: "QA-QE-1974",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(20),
      notes: "Provider · Petroleum / Energy — LNG & gas",
    },
    {
      id: "BEN-DEMO-0018",
      type: "corporate",
      name: "Equinor ASA",
      alias: "Equinor",
      accountNumber: "30001234567",
      iban: "NO8330001234567",
      swiftBic: "DNBANOKK",
      bankName: "DNB Bank ASA",
      bankAddress: "Dronning Eufemias gate 30, 0191 Oslo",
      bankCountry: "Norway",
      beneficiaryAddress: "Forusbeen 50",
      beneficiaryCity: "Stavanger",
      beneficiaryCountry: "Norway",
      beneficiaryPostalCode: "4035",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(78),
      lastUsed: daysAgo(34),
      totalTransactions: 5,
      totalVolume: 142_000_000,
      registrationNumber: "NO-923609016",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(28),
      notes: "Provider · Petroleum / Energy — producer (oil, gas, wind)",
    },
    {
      id: "BEN-DEMO-0019",
      type: "corporate",
      name: "Eni Trading & Shipping S.p.A.",
      alias: "Eni Trading",
      accountNumber: "0300203280123456789012",
      iban: "IT96S0300203280123456789012",
      swiftBic: "BCITITMM",
      bankName: "Intesa Sanpaolo S.p.A.",
      bankAddress: "Piazza San Carlo 156, 10121 Torino",
      bankCountry: "Italy",
      beneficiaryAddress: "Piazzale Enrico Mattei 1",
      beneficiaryCity: "Rome",
      beneficiaryCountry: "Italy",
      beneficiaryPostalCode: "00144",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(70),
      lastUsed: daysAgo(37),
      totalTransactions: 4,
      totalVolume: 97_000_000,
      registrationNumber: "IT-00484960588",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(30),
      notes: "Provider · Petroleum / Energy — integrated major",
    },
    {
      id: "BEN-DEMO-0020",
      type: "corporate",
      name: "Petroliam Nasional Berhad (PETRONAS)",
      alias: "PETRONAS",
      accountNumber: "5141880023456",
      swiftBic: "MBBEMYKL",
      bankName: "Malayan Banking Berhad (Maybank)",
      bankAddress: "Menara Maybank, 100 Jalan Tun Perak, Kuala Lumpur",
      bankCountry: "Malaysia",
      beneficiaryAddress: "Tower 1, PETRONAS Twin Towers, KLCC",
      beneficiaryCity: "Kuala Lumpur",
      beneficiaryCountry: "Malaysia",
      beneficiaryPostalCode: "50088",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(66),
      lastUsed: daysAgo(41),
      totalTransactions: 3,
      totalVolume: 78_000_000,
      registrationNumber: "MY-20076-K",
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(32),
      notes: "Provider · Petroleum / Energy — national oil company",
    },
    {
      id: "BEN-DEMO-0021",
      type: "corporate",
      name: "Sonatrach",
      alias: "Sonatrach Algiers",
      accountNumber: "00021000011130000000570",
      iban: "DZ580002100001113000000570",
      swiftBic: "BEXADZAL",
      bankName: "Banque Extérieure d'Algérie",
      bankAddress: "Boulevard Mohamed V, Algiers 16000",
      bankCountry: "Algeria",
      beneficiaryAddress: "Djenane El Malik, Hydra",
      beneficiaryCity: "Algiers",
      beneficiaryCountry: "Algeria",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(60),
      lastUsed: daysAgo(44),
      totalTransactions: 2,
      totalVolume: 64_000_000,
      registrationNumber: "DZ-SH-1963",
      kycVerified: true,
      riskLevel: "medium",
      amlScreeningDate: dateAgo(35),
      notes: "Provider · Petroleum / Energy — national oil company",
    },

    // === Finance / Banking — correspondent & settlement institutions ========
    {
      id: "BEN-DEMO-0022",
      type: "financial_institution",
      name: "JPMorgan Chase Bank N.A.",
      alias: "JPMorgan New York",
      accountNumber: "0048871220",
      swiftBic: "CHASUS33",
      bankName: "JPMorgan Chase Bank N.A.",
      bankAddress: "383 Madison Avenue, New York, NY 10017",
      bankCountry: "United States",
      beneficiaryAddress: "383 Madison Avenue",
      beneficiaryCity: "New York",
      beneficiaryCountry: "United States",
      beneficiaryPostalCode: "10017",
      currency: "USD",
      status: "active",
      isFavorite: true,
      createdAt: daysAgo(160),
      lastUsed: daysAgo(8),
      totalTransactions: 21,
      totalVolume: 720_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(16),
      notes: "Finance / Banking — USD correspondent & clearing",
    },
    {
      id: "BEN-DEMO-0023",
      type: "financial_institution",
      name: "Citibank N.A.",
      alias: "Citi New York",
      accountNumber: "0091824470",
      swiftBic: "CITIUS33",
      bankName: "Citibank N.A.",
      bankAddress: "388 Greenwich Street, New York, NY 10013",
      bankCountry: "United States",
      beneficiaryAddress: "388 Greenwich Street",
      beneficiaryCity: "New York",
      beneficiaryCountry: "United States",
      beneficiaryPostalCode: "10013",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(150),
      lastUsed: daysAgo(18),
      totalTransactions: 15,
      totalVolume: 503_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(22),
      notes: "Finance / Banking — USD correspondent & trade finance",
    },
    {
      id: "BEN-DEMO-0024",
      type: "financial_institution",
      name: "HSBC Bank plc",
      alias: "HSBC London",
      accountNumber: "40127612345678",
      iban: "GB71HBUK40127612345678",
      swiftBic: "HBUKGB4B",
      bankName: "HSBC UK Bank plc",
      bankAddress: "8 Canada Square, London E14 5HQ",
      bankCountry: "United Kingdom",
      beneficiaryAddress: "8 Canada Square",
      beneficiaryCity: "London",
      beneficiaryCountry: "United Kingdom",
      beneficiaryPostalCode: "E14 5HQ",
      currency: "GBP",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(140),
      lastUsed: daysAgo(20),
      totalTransactions: 12,
      totalVolume: 367_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(21),
      notes: "Finance / Banking — multi-currency correspondent",
    },
    {
      id: "BEN-DEMO-0025",
      type: "financial_institution",
      name: "Deutsche Bank AG",
      alias: "Deutsche Bank Frankfurt",
      accountNumber: "0532013000",
      iban: "DE94500700100123456789",
      swiftBic: "DEUTDEFF",
      bankName: "Deutsche Bank AG",
      bankAddress: "Taunusanlage 12, 60325 Frankfurt am Main",
      bankCountry: "Germany",
      beneficiaryAddress: "Taunusanlage 12",
      beneficiaryCity: "Frankfurt",
      beneficiaryCountry: "Germany",
      beneficiaryPostalCode: "60325",
      currency: "EUR",
      status: "active",
      isFavorite: true,
      createdAt: daysAgo(136),
      lastUsed: daysAgo(12),
      totalTransactions: 17,
      totalVolume: 512_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(15),
      notes: "Finance / Banking — EUR correspondent & custody",
    },
    {
      id: "BEN-DEMO-0026",
      type: "financial_institution",
      name: "UBS Switzerland AG",
      alias: "UBS Zürich",
      accountNumber: "0235012345678",
      iban: "CH8800235012345678901",
      swiftBic: "UBSWCHZH80A",
      bankName: "UBS Switzerland AG",
      bankAddress: "Bahnhofstrasse 45, 8001 Zürich",
      bankCountry: "Switzerland",
      beneficiaryAddress: "Bahnhofstrasse 45",
      beneficiaryCity: "Zürich",
      beneficiaryCountry: "Switzerland",
      beneficiaryPostalCode: "8001",
      currency: "CHF",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(130),
      lastUsed: daysAgo(16),
      totalTransactions: 14,
      totalVolume: 441_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(18),
      notes: "Finance / Banking — CHF correspondent & private banking",
    },
    {
      id: "BEN-DEMO-0027",
      type: "financial_institution",
      name: "BNP Paribas SA",
      alias: "BNP Paribas Paris",
      accountNumber: "30006000011234567890189",
      iban: "FR8730006000011234567890185",
      swiftBic: "BNPAFRPP",
      bankName: "BNP Paribas SA",
      bankAddress: "16 Boulevard des Italiens, 75009 Paris",
      bankCountry: "France",
      beneficiaryAddress: "16 Boulevard des Italiens",
      beneficiaryCity: "Paris",
      beneficiaryCountry: "France",
      beneficiaryPostalCode: "75009",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(124),
      lastUsed: daysAgo(23),
      totalTransactions: 10,
      totalVolume: 318_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(25),
      notes: "Finance / Banking — EUR correspondent & trade finance",
    },
    {
      id: "BEN-DEMO-0028",
      type: "financial_institution",
      name: "Standard Chartered Bank",
      alias: "Standard Chartered London",
      accountNumber: "60910412345678",
      iban: "GB08SCBL60910412345678",
      swiftBic: "SCBLGB2L",
      bankName: "Standard Chartered Bank",
      bankAddress: "1 Basinghall Avenue, London EC2V 5DD",
      bankCountry: "United Kingdom",
      beneficiaryAddress: "1 Basinghall Avenue",
      beneficiaryCity: "London",
      beneficiaryCountry: "United Kingdom",
      beneficiaryPostalCode: "EC2V 5DD",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(116),
      lastUsed: daysAgo(27),
      totalTransactions: 8,
      totalVolume: 247_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(24),
      notes: "Finance / Banking — emerging-markets trade finance",
    },
    {
      id: "BEN-DEMO-0029",
      type: "financial_institution",
      name: "Euroclear Bank SA/NV",
      alias: "Euroclear Brussels",
      accountNumber: "096123456769",
      iban: "BE71096123456769",
      swiftBic: "MGTCBEBE",
      bankName: "Euroclear Bank SA/NV",
      bankAddress: "1 Boulevard du Roi Albert II, 1210 Brussels",
      bankCountry: "Belgium",
      beneficiaryAddress: "1 Boulevard du Roi Albert II",
      beneficiaryCity: "Brussels",
      beneficiaryCountry: "Belgium",
      beneficiaryPostalCode: "1210",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(108),
      lastUsed: daysAgo(30),
      totalTransactions: 7,
      totalVolume: 224_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(26),
      notes: "Finance / Banking — international securities depository",
    },
    {
      id: "BEN-DEMO-0030",
      type: "financial_institution",
      name: "Clearstream Banking SA",
      alias: "Clearstream Luxembourg",
      accountNumber: "0030123456789000",
      iban: "LU910030123456789000",
      swiftBic: "CEDELULL",
      bankName: "Clearstream Banking SA",
      bankAddress: "42 Avenue John F. Kennedy, 1855 Luxembourg",
      bankCountry: "Luxembourg",
      beneficiaryAddress: "42 Avenue John F. Kennedy",
      beneficiaryCity: "Luxembourg",
      beneficiaryCountry: "Luxembourg",
      beneficiaryPostalCode: "1855",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(100),
      lastUsed: daysAgo(35),
      totalTransactions: 6,
      totalVolume: 188_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(27),
      notes: "Finance / Banking — international securities depository",
    },
    {
      id: "BEN-DEMO-0031",
      type: "financial_institution",
      name: "The Bank of New York Mellon",
      alias: "BNY Mellon",
      accountNumber: "8900215447",
      swiftBic: "IRVTUS3N",
      bankName: "The Bank of New York Mellon",
      bankAddress: "240 Greenwich Street, New York, NY 10286",
      bankCountry: "United States",
      beneficiaryAddress: "240 Greenwich Street",
      beneficiaryCity: "New York",
      beneficiaryCountry: "United States",
      beneficiaryPostalCode: "10286",
      currency: "USD",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(94),
      lastUsed: daysAgo(39),
      totalTransactions: 5,
      totalVolume: 161_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(29),
      notes: "Finance / Banking — global custody & asset servicing",
    },
    {
      id: "BEN-DEMO-0032",
      type: "financial_institution",
      name: "Banco Santander S.A.",
      alias: "Santander Madrid",
      accountNumber: "00491500051234567892",
      iban: "ES6000491500051234567892",
      swiftBic: "BSCHESMM",
      bankName: "Banco Santander S.A.",
      bankAddress: "Avenida de Cantabria s/n, 28660 Boadilla del Monte, Madrid",
      bankCountry: "Spain",
      beneficiaryAddress: "Paseo de Pereda 9-12",
      beneficiaryCity: "Santander",
      beneficiaryCountry: "Spain",
      beneficiaryPostalCode: "39004",
      currency: "EUR",
      status: "active",
      isFavorite: false,
      createdAt: daysAgo(88),
      lastUsed: daysAgo(42),
      totalTransactions: 4,
      totalVolume: 119_000_000,
      kycVerified: true,
      riskLevel: "low",
      amlScreeningDate: dateAgo(31),
      notes: "Finance / Banking — EUR correspondent",
    },
  ]
}
