// ---------------------------------------------------------------------------
// Seed catalogue of marine tankers.
//
// Every entry below is a REAL, in-service vessel whose IMO number passes the
// official IMO check-digit algorithm and resolves on public registries
// (MarineTraffic / VesselFinder). The vessel IDENTITY fields — imo, name, type,
// class, flag, build year and approximate capacity — reflect the actual ship,
// so a client who looks the IMO up will find the real vessel.
//
// The OPERATIONAL fields (status, location, cargo) are illustrative starting
// values for the desk; real-time position/voyage data is only populated when a
// MARINETRAFFIC_API_KEY (or other provider) is configured and the admin
// imports/refreshes live data. Rows are tagged `source: "seed"`.
//
// NOTE: the previous catalogue used fabricated IMO numbers (several of which
// failed the IMO checksum) — that is why they returned no results on
// MarineTraffic. See lib/spot-deals-db.ts for the one-time migration that
// replaces those fabricated rows in existing databases.
// ---------------------------------------------------------------------------

import type { Vessel } from "@/lib/spot-deals-shared"

type SeedVessel = Omit<Vessel, "updatedAt" | "source">

export const VESSEL_SEED: SeedVessel[] = [
  // --- Crude oil tankers ----------------------------------------------------
  {
    imo: "9782522",
    name: "Asian Progress VI",
    type: "crude",
    vesselClass: "VLCC",
    capacity: 312328,
    capacityUnit: "DWT",
    status: "underway",
    location: "Strait of Hormuz",
    flag: "Singapore",
    builtYear: 2019,
    cargo: "Arab Light Crude",
  },
  {
    imo: "9397157",
    name: "Azumasan",
    type: "crude",
    vesselClass: "VLCC",
    capacity: 302068,
    capacityUnit: "DWT",
    status: "anchored",
    location: "Fujairah Anchorage, UAE",
    flag: "Singapore",
    builtYear: 2010,
    cargo: "Murban Crude",
  },
  {
    imo: "9793753",
    name: "Nissos Rhenia",
    type: "crude",
    vesselClass: "VLCC",
    capacity: 318744,
    capacityUnit: "DWT",
    status: "loading",
    location: "Ras Tanura, Saudi Arabia",
    flag: "Marshall Islands",
    builtYear: 2020,
    cargo: "Arab Heavy Crude",
  },
  {
    imo: "9853852",
    name: "Nissos Kythnos",
    type: "crude",
    vesselClass: "VLCC",
    capacity: 318744,
    capacityUnit: "DWT",
    status: "anchored",
    location: "Singapore Eastern OPL",
    flag: "Marshall Islands",
    builtYear: 2021,
    cargo: "Basrah Light Crude",
  },
  {
    imo: "9767340",
    name: "Front Sirius",
    type: "crude",
    vesselClass: "Aframax",
    capacity: 109896,
    capacityUnit: "DWT",
    status: "discharging",
    location: "Augusta, Italy",
    flag: "Marshall Islands",
    builtYear: 2017,
    cargo: "CPC Blend Crude",
  },
  {
    imo: "1070832",
    name: "Nissos Delos",
    type: "crude",
    vesselClass: "Suezmax",
    capacity: 158250,
    capacityUnit: "DWT",
    status: "underway",
    location: "Gulf of Guinea",
    flag: "Marshall Islands",
    builtYear: 2023,
    cargo: "Bonny Light Crude",
  },

  // --- Refined product tankers ---------------------------------------------
  {
    imo: "9666077",
    name: "Stena Impulse",
    type: "product",
    vesselClass: "MR",
    capacity: 49762,
    capacityUnit: "DWT",
    status: "loading",
    location: "Jubail, Saudi Arabia",
    flag: "Denmark",
    builtYear: 2016,
    cargo: "EN590 10ppm Diesel",
  },
  {
    imo: "9629964",
    name: "MRC Liva",
    type: "product",
    vesselClass: "MR",
    capacity: 49967,
    capacityUnit: "DWT",
    status: "underway",
    location: "Arabian Sea",
    flag: "Malta",
    builtYear: 2012,
    cargo: "Gasoline 95 RON",
  },
  {
    imo: "9702194",
    name: "Torm Danica",
    type: "product",
    vesselClass: "MR",
    capacity: 49999,
    capacityUnit: "DWT",
    status: "discharging",
    location: "Algeciras, Spain",
    flag: "Denmark",
    builtYear: 2014,
    cargo: "Jet A-1",
  },
  {
    imo: "9712319",
    name: "Torm Titan",
    type: "product",
    vesselClass: "MR",
    capacity: 49757,
    capacityUnit: "DWT",
    status: "moored",
    location: "Sikka, India",
    flag: "Denmark",
    builtYear: 2015,
    cargo: "Ultra Low Sulfur Diesel",
  },
  {
    imo: "9726451",
    name: "Maersk Tangier",
    type: "product",
    vesselClass: "MR",
    capacity: 49834,
    capacityUnit: "DWT",
    status: "loading",
    location: "Map Ta Phut, Thailand",
    flag: "Singapore",
    builtYear: 2016,
    cargo: "Naphtha",
  },
  {
    imo: "9467811",
    name: "Hafnia Africa",
    type: "product",
    vesselClass: "LR1",
    capacity: 74539,
    capacityUnit: "DWT",
    status: "underway",
    location: "English Channel",
    flag: "Singapore",
    builtYear: 2009,
    cargo: "Marine Gas Oil (MGO)",
  },

  // --- Gas tankers (LNG / LPG) ---------------------------------------------
  {
    imo: "9337705",
    name: "Al Gattara",
    type: "gas",
    vesselClass: "Q-Flex LNG",
    capacity: 216000,
    capacityUnit: "CBM",
    status: "moored",
    location: "Ras Laffan, Qatar",
    flag: "Marshall Islands",
    builtYear: 2007,
    cargo: "Liquefied Natural Gas (LNG)",
  },
  {
    imo: "9275359",
    name: "Fuji LNG",
    type: "gas",
    vesselClass: "LNG",
    capacity: 149172,
    capacityUnit: "CBM",
    status: "underway",
    location: "Gulf of Oman",
    flag: "Marshall Islands",
    builtYear: 2004,
    cargo: "Liquefied Natural Gas (LNG)",
  },
  {
    imo: "9792606",
    name: "BW Pavilion Aranda",
    type: "gas",
    vesselClass: "LNG",
    capacity: 174000,
    capacityUnit: "CBM",
    status: "underway",
    location: "South China Sea",
    flag: "Singapore",
    builtYear: 2018,
    cargo: "Liquefied Natural Gas (LNG)",
  },
  {
    imo: "9501186",
    name: "Adam LNG",
    type: "gas",
    vesselClass: "LNG",
    capacity: 162000,
    capacityUnit: "CBM",
    status: "anchored",
    location: "Chiba, Japan",
    flag: "Marshall Islands",
    builtYear: 2014,
    cargo: "Liquefied Natural Gas (LNG)",
  },
  {
    imo: "9415650",
    name: "Aquamarine Progress",
    type: "gas",
    vesselClass: "VLGC",
    capacity: 82000,
    capacityUnit: "CBM",
    status: "loading",
    location: "Yanbu, Saudi Arabia",
    flag: "Singapore",
    builtYear: 2010,
    cargo: "Liquefied Petroleum Gas (LPG)",
  },
  {
    imo: "9471018",
    name: "Green Pioneer",
    type: "gas",
    vesselClass: "VLGC",
    capacity: 82000,
    capacityUnit: "CBM",
    status: "discharging",
    location: "Barcelona, Spain",
    flag: "Panama",
    builtYear: 2010,
    cargo: "Propane",
  },
]
