// ---------------------------------------------------------------------------
// Seed catalogue of marine tankers.
//
// Realistic sample fleet across the three tanker families (crude, refined
// product, gas) used to populate the vessel database on first run so the desk
// has data to work with WITHOUT requiring a paid MarineTraffic API key. Each
// entry carries the fields the spec asks for: IMO, name, type, capacity,
// status, last known location and cargo. Rows are tagged `source: "seed"` so
// admins can tell them apart from manually-entered or API-imported vessels.
//
// These are representative sample specifications for demonstration; if a
// MARINETRAFFIC_API_KEY is configured, admins can import/refresh live data.
// ---------------------------------------------------------------------------

import type { Vessel } from "@/lib/spot-deals-shared"

type SeedVessel = Omit<Vessel, "updatedAt" | "source">

export const VESSEL_SEED: SeedVessel[] = [
  // --- Crude oil tankers ----------------------------------------------------
  {
    imo: "9512331",
    name: "Pacific Triton",
    type: "crude",
    vesselClass: "VLCC",
    capacity: 318000,
    capacityUnit: "DWT",
    status: "underway",
    location: "Strait of Hormuz",
    flag: "Marshall Islands",
    builtYear: 2012,
    cargo: "Arab Light Crude",
  },
  {
    imo: "9402585",
    name: "Aegean Star",
    type: "crude",
    vesselClass: "Suezmax",
    capacity: 158000,
    capacityUnit: "DWT",
    status: "anchored",
    location: "Fujairah Anchorage, UAE",
    flag: "Greece",
    builtYear: 2009,
    cargo: "Basrah Light Crude",
  },
  {
    imo: "9598705",
    name: "Nordic Falcon",
    type: "crude",
    vesselClass: "Aframax",
    capacity: 114000,
    capacityUnit: "DWT",
    status: "loading",
    location: "Primorsk, Russia",
    flag: "Norway",
    builtYear: 2014,
    cargo: "Urals Crude",
  },
  {
    imo: "9276604",
    name: "Gulf Sovereign",
    type: "crude",
    vesselClass: "VLCC",
    capacity: 300000,
    capacityUnit: "DWT",
    status: "moored",
    location: "Ras Tanura, Saudi Arabia",
    flag: "Liberia",
    builtYear: 2011,
    cargo: "Arab Heavy Crude",
  },
  {
    imo: "9733521",
    name: "Atlantic Meridian",
    type: "crude",
    vesselClass: "Suezmax",
    capacity: 156000,
    capacityUnit: "DWT",
    status: "underway",
    location: "Gulf of Guinea",
    flag: "Panama",
    builtYear: 2016,
    cargo: "Bonny Light Crude",
  },
  {
    imo: "9281295",
    name: "Caspian Pioneer",
    type: "crude",
    vesselClass: "Aframax",
    capacity: 107000,
    capacityUnit: "DWT",
    status: "discharging",
    location: "Augusta, Italy",
    flag: "Malta",
    builtYear: 2008,
    cargo: "CPC Blend Crude",
  },
  {
    imo: "9844112",
    name: "Eastern Dawn",
    type: "crude",
    vesselClass: "VLCC",
    capacity: 320000,
    capacityUnit: "DWT",
    status: "anchored",
    location: "Singapore Eastern OPL",
    flag: "Singapore",
    builtYear: 2019,
    cargo: "Murban Crude",
  },
  {
    imo: "9410788",
    name: "Baltic Empress",
    type: "crude",
    vesselClass: "Aframax",
    capacity: 110000,
    capacityUnit: "DWT",
    status: "idle",
    location: "Rotterdam, Netherlands",
    flag: "Denmark",
    builtYear: 2010,
    cargo: "—",
  },

  // --- Refined product tankers ---------------------------------------------
  {
    imo: "9685213",
    name: "Crystal Harmony",
    type: "product",
    vesselClass: "LR2",
    capacity: 115000,
    capacityUnit: "DWT",
    status: "loading",
    location: "Jubail, Saudi Arabia",
    flag: "Marshall Islands",
    builtYear: 2015,
    cargo: "Jet A-1",
  },
  {
    imo: "9523146",
    name: "Sapphire Trader",
    type: "product",
    vesselClass: "LR1",
    capacity: 74000,
    capacityUnit: "DWT",
    status: "underway",
    location: "Arabian Sea",
    flag: "Singapore",
    builtYear: 2013,
    cargo: "EN590 10ppm Diesel",
  },
  {
    imo: "9777349",
    name: "Ocean Liberty",
    type: "product",
    vesselClass: "MR",
    capacity: 49000,
    capacityUnit: "DWT",
    status: "anchored",
    location: "Houston Ship Channel, USA",
    flag: "USA",
    builtYear: 2017,
    cargo: "Gasoline 95 RON",
  },
  {
    imo: "9601542",
    name: "Mediterranean Glory",
    type: "product",
    vesselClass: "MR",
    capacity: 51000,
    capacityUnit: "DWT",
    status: "discharging",
    location: "Algeciras, Spain",
    flag: "Italy",
    builtYear: 2012,
    cargo: "Jet A-1",
  },
  {
    imo: "9812007",
    name: "Indus Navigator",
    type: "product",
    vesselClass: "LR2",
    capacity: 113000,
    capacityUnit: "DWT",
    status: "moored",
    location: "Sikka, India",
    flag: "India",
    builtYear: 2018,
    cargo: "Ultra Low Sulfur Diesel",
  },
  {
    imo: "9356894",
    name: "Coral Endeavour",
    type: "product",
    vesselClass: "MR",
    capacity: 47000,
    capacityUnit: "DWT",
    status: "underway",
    location: "English Channel",
    flag: "Netherlands",
    builtYear: 2007,
    cargo: "Marine Gas Oil (MGO)",
  },
  {
    imo: "9729518",
    name: "Andaman Spirit",
    type: "product",
    vesselClass: "LR1",
    capacity: 75000,
    capacityUnit: "DWT",
    status: "loading",
    location: "Map Ta Phut, Thailand",
    flag: "Thailand",
    builtYear: 2016,
    cargo: "Naphtha",
  },

  // --- Gas tankers (LNG / LPG) ---------------------------------------------
  {
    imo: "9709823",
    name: "Polar Aurora",
    type: "gas",
    vesselClass: "LNG",
    capacity: 174000,
    capacityUnit: "CBM",
    status: "underway",
    location: "Gulf of Oman",
    flag: "Bermuda",
    builtYear: 2018,
    cargo: "Liquefied Natural Gas (LNG)",
  },
  {
    imo: "9655311",
    name: "Qatar Vision",
    type: "gas",
    vesselClass: "Q-Flex LNG",
    capacity: 210000,
    capacityUnit: "CBM",
    status: "moored",
    location: "Ras Laffan, Qatar",
    flag: "Marshall Islands",
    builtYear: 2014,
    cargo: "Liquefied Natural Gas (LNG)",
  },
  {
    imo: "9388552",
    name: "Arctic Brilliance",
    type: "gas",
    vesselClass: "VLGC",
    capacity: 84000,
    capacityUnit: "CBM",
    status: "loading",
    location: "Yanbu, Saudi Arabia",
    flag: "Panama",
    builtYear: 2009,
    cargo: "Liquefied Petroleum Gas (LPG)",
  },
  {
    imo: "9821458",
    name: "Helios Carrier",
    type: "gas",
    vesselClass: "VLGC",
    capacity: 91000,
    capacityUnit: "CBM",
    status: "anchored",
    location: "Chiba, Japan",
    flag: "Japan",
    builtYear: 2019,
    cargo: "Propane",
  },
  {
    imo: "9512549",
    name: "Iberian Frost",
    type: "gas",
    vesselClass: "Midsize LPG",
    capacity: 38000,
    capacityUnit: "CBM",
    status: "discharging",
    location: "Barcelona, Spain",
    flag: "Spain",
    builtYear: 2011,
    cargo: "Butane",
  },
  {
    imo: "9901337",
    name: "Pacific Methane",
    type: "gas",
    vesselClass: "LNG",
    capacity: 180000,
    capacityUnit: "CBM",
    status: "underway",
    location: "South China Sea",
    flag: "Singapore",
    builtYear: 2021,
    cargo: "Liquefied Natural Gas (LNG)",
  },
]
